### PR TITLE
Configurable host:port 

### PR DESCRIPTION
**Pull request by eyedeekay**
Sorry about mangling the history last time I submitted this. I tried to rebase and ended up making it worse. Except for the fact that ports can now be configured by passing an integer or a string, the changes are all the same.

### CODE REVIEW

**Comment by cryptix** [comment]
oh damn! I thought I merged this already! I'm Sorry if I left you hanging here...

**Comment by cryptix** [comment]
One thing I'm not so sure about is the signature of `func SetAddr(s ...interface{})` for instance... I'd rather have the concrete types and multiple functions than loose the safety at compile time.

**Comment by eyedeekay** [comment]
I just figured you were busy, I just experimented based on my branch where I wanted to use the new features. Plus I don't think my applications are very widely used yet. I'll ditch the interfaces and push the new changes shortly.

**Comment by eyedeekay** [comment]
Should be ready to go.

**Comment by eyedeekay** [comment]
Have I missed anything?

**Comment by cryptix** [comment]
Wow sorry. I’ll just merge this now.

**Pull request merged**
