### PR TITLE
Added Reduce/Close on idle options

### PR DESCRIPTION
**Pull request by eyedeekay**
I made it possible for users to configure reducing and closing idle tunnels. Nothing much else to it.

### CODE REVIEW

**Comment by cryptix** [comment]
This looks good!

Will take one more look when I’m not on mobile and probably squash this into one commit then and merge it.

**Comment by eyedeekay** [comment]
I forgot to comment the new option functions correctly. Incidentally, do you know why when I send you a pull request it repeats all that stuff from before? I feel like I must be missing something I did by mistake.

**Comment by eyedeekay** [comment]
Did my best to squash them down to something sensible.

**Comment by cryptix** [comment]
thanks!

I guess you opened the PR from a different branch..? anyways.. looks much better now history-wise.

**Comment by cryptix** [comment]
I tried to merge this manually but now see that the parents of the branches diverge differently.

**Pull request closed without merging**
